### ISSUE TITLE
Testing package with dartdevc does not work

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/code_builder#122]
I tried adding this to `pubspec.yaml`:

```yaml
transformers:
  - test/pub_serve:
      $include: test/**_test.dart
```

And then ran this:

```bash
$ pub serve --web-compiler=dartdevc
$ pub run test -p chrome --pub-serve=8080
```

Lots of things explode, and my console is so full of errors I can't even diagnose an issue.

/cc @jakemac53 @kevmoo @vsmenon
